Line 234: Unexpected token {
> ...se(t) } catch { return e } } t...
